# Generated by Django 3.0.4 on 2020-03-12 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='goods_total',
        ),
    ]
