# Generated by Django 3.0.4 on 2020-03-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20200311_1418'),
        ('buyer', '0002_remove_cart_goods_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=36, unique=True, verbose_name='订单号')),
                ('order_date', models.DateField(auto_now=True, verbose_name='订单创建时间')),
                ('order_status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '待发货'), (4, '已发货'), (5, '拒收'), (6, '已完成')], verbose_name='订单状态')),
                ('order_total', models.FloatField(verbose_name='订单总价')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.LoginUser', verbose_name='买家')),
            ],
            options={
                'db_table': 'pay_order',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_price', models.FloatField(verbose_name='商品的单价')),
                ('goods_count', models.IntegerField(verbose_name='购买的单品的数量')),
                ('goods_total_price', models.FloatField(verbose_name='购买的单品的总金额')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.PayOrder')),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
    ]
