# Generated by Django 3.0.4 on 2020-03-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_orderinfo_payorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payorder',
            name='order_total',
        ),
    ]
