# Generated by Django 3.0.4 on 2020-03-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_remove_payorder_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorder',
            name='order_address',
            field=models.CharField(default='beijing', max_length=1024, verbose_name='送货地址'),
            preserve_default=False,
        ),
    ]
