# Generated by Django 3.0.4 on 2020-03-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20200311_1418'),
        ('buyer', '0005_payorder_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='收货人')),
                ('sitearea', models.TextField(verbose_name='收货地址')),
                ('code', models.CharField(max_length=8, verbose_name='邮政编码')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('status', models.IntegerField(choices=[(1, '默认地址'), (2, '历史地址'), (3, '禁用地址')], default=1, verbose_name='地址状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.LoginUser', verbose_name='用户')),
            ],
        ),
    ]
