# Generated by Django 3.0.4 on 2020-03-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_usersite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersite',
            table='user_site',
        ),
    ]
