# Generated by Django 3.0.4 on 2020-03-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20200311_1418'),
        ('buyer', '0007_auto_20200321_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(auto_now=True, verbose_name='浏览时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Goods', verbose_name='浏览商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.LoginUser', verbose_name='浏览用户')),
            ],
            options={
                'db_table': 'look_history',
            },
        ),
    ]
