# Generated by Django 3.0.4 on 2020-03-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_lookhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='order_number',
            field=models.CharField(max_length=8, unique=True, verbose_name='订单号'),
        ),
    ]
