# Generated by Django 3.0.4 on 2020-03-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('username', models.CharField(default='', max_length=32, verbose_name='用户名')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('photo', models.ImageField(default='img/gtl.jpg', upload_to='img', verbose_name='图片')),
                ('user_type', models.IntegerField(choices=[(0, '卖家'), (1, '买家')], default=1, verbose_name='用户身份')),
            ],
            options={
                'db_table': 'loginuser',
            },
        ),
    ]
