# Generated by Django 3.0.4 on 2020-03-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_label', models.CharField(max_length=32, verbose_name='类型标签')),
                ('type_description', models.TextField(verbose_name='类型的描述')),
                ('type_picture', models.ImageField(max_length=64, upload_to='', verbose_name='类型的图片')),
            ],
            options={
                'db_table': 'goods_type',
            },
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(default='img/touxiang.png', upload_to='img', verbose_name='图片'),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=11, verbose_name='商品编号')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名字')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_count', models.IntegerField(verbose_name='商品数量')),
                ('goods_location', models.CharField(max_length=32, verbose_name='商品产地')),
                ('goods_safe_date', models.IntegerField(verbose_name='商品保质期')),
                ('goods_pro_time', models.DateTimeField(auto_now=True, verbose_name='生成日期')),
                ('goods_status', models.IntegerField(choices=[(0, '下架'), (1, '在售')], default=1, verbose_name='商品状态')),
                ('goods_picture', models.ImageField(default='img/1.jpg', upload_to='img', verbose_name='商品的图片')),
                ('goods_description', models.TextField(default='good goods', verbose_name='商品的描述')),
                ('goods_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.LoginUser')),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.GoodsType')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
