# Generated by Django 3.0.4 on 2020-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200311_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='type_picture',
            field=models.ImageField(max_length=64, upload_to='img/goodstype/', verbose_name='类型的图片'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(default='img/user/touxiang.png', upload_to='img/user/', verbose_name='图片'),
        ),
    ]
